import type { ShoppingSection } from "@/types/enums";

/**
 * Palavras-chave por seção. A normalização faz:
 *   `name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")`
 * e checa se alguma keyword está contida (match por `includes`).
 * Primeira seção a dar match vence.
 */
const KEYWORDS: { section: ShoppingSection; words: string[] }[] = [
  {
    section: "frutas_verduras",
    words: [
      "banana",
      "maca",
      "maça",
      "maçã",
      "laranja",
      "tomate",
      "cebola",
      "alface",
      "batata",
      "cenoura",
      "mamao",
      "mamão",
      "abacate",
      "limao",
      "limão",
      "manga",
      "uva",
      "pera",
      "pimentao",
      "pimentão",
      "pimenta",
      "brocolis",
      "brócolis",
      "couve",
      "espinafre",
      "pepino",
      "abobrinha",
      "abobora",
      "abóbora",
      "beterraba",
      "chuchu",
      "melancia",
      "melao",
      "melão",
      "rucula",
      "rúcula",
      "agriao",
      "agrião",
      "salsinha",
      "cebolinha",
      "coentro",
      "alho",
      "gengibre",
      "repolho",
      "morango",
      "kiwi",
      "abacaxi",
      "mexerica",
      "tangerina",
    ],
  },
  {
    section: "padaria",
    words: [
      "pao",
      "pão",
      "biscoito",
      "bolacha",
      "baguete",
      "croissant",
      "bolo",
      "torta",
      "rosca",
    ],
  },
  {
    section: "carnes_peixes",
    words: [
      "carne",
      "frango",
      "peixe",
      "salmao",
      "salmão",
      "tilapia",
      "tilápia",
      "patinho",
      "coxa",
      "sobrecoxa",
      "file",
      "filé",
      "filet",
      "alcatra",
      "picanha",
      "maminha",
      "fraldinha",
      "costela",
      "salsicha",
      "linguica",
      "linguiça",
      "bacon",
      "presunto",
      "hamburguer",
      "hambúrguer",
      "mortadela",
      "salami",
      "salame",
    ],
  },
  {
    section: "frios_laticinios",
    words: [
      "queijo",
      "mussarela",
      "muçarela",
      "iogurte",
      "leite",
      "manteiga",
      "requeijao",
      "requeijão",
      "ricota",
      "nata",
      "cream cheese",
      "cottage",
      "parmesao",
      "parmesão",
      "creme de leite",
      "leite condensado",
    ],
  },
  {
    section: "bebidas",
    words: [
      "cerveja",
      "vinho",
      "refrigerante",
      "suco",
      "agua",
      "água",
      "cafe",
      "café",
      "cha",
      "chá",
      "whisky",
      "cachaca",
      "cachaça",
      "vodka",
      "energetico",
      "energético",
      "coca",
      "guarana",
      "guaraná",
      "pepsi",
      "sprite",
      "fanta",
    ],
  },
  {
    section: "congelados",
    words: [
      "sorvete",
      "pizza congelada",
      "lasanha congelada",
      "nuggets",
      "batata frita",
      "polenta",
      "hamburguer congelado",
    ],
  },
  {
    section: "limpeza",
    words: [
      "sabao",
      "sabão",
      "detergente",
      "desinfetante",
      "amaciante",
      "agua sanitaria",
      "água sanitária",
      "cloro",
      "lustra",
      "vassoura",
      "rodo",
      "esponja",
      "saco de lixo",
      "papel toalha",
      "alcool",
      "álcool",
      "veja",
      "pinho",
    ],
  },
  {
    section: "higiene",
    words: [
      "shampoo",
      "xampu",
      "condicionador",
      "sabonete",
      "creme dental",
      "pasta de dente",
      "fio dental",
      "desodorante",
      "papel higienico",
      "papel higiênico",
      "absorvente",
      "fralda",
      "lencos umedecidos",
      "lenços umedecidos",
      "escova de dente",
      "enxaguante",
    ],
  },
  {
    section: "mercearia",
    words: [
      "arroz",
      "feijao",
      "feijão",
      "macarrao",
      "macarrão",
      "farinha",
      "acucar",
      "açúcar",
      "sal",
      "oleo",
      "óleo",
      "azeite",
      "vinagre",
      "molho",
      "ketchup",
      "mostarda",
      "maionese",
      "atum",
      "sardinha",
      "milho",
      "ervilha",
      "aveia",
      "granola",
      "cereal",
      "achocolatado",
      "nescau",
      "chocolate",
      "bala",
      "tempero",
      "caldo",
    ],
  },
];

export function normalizeName(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

export function guessSection(name: string): ShoppingSection {
  const normalized = normalizeName(name);
  for (const { section, words } of KEYWORDS) {
    for (const w of words) {
      if (normalized.includes(normalizeName(w))) return section;
    }
  }
  return "outros";
}
